use_nerdfont = true

[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#eba0ac"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#845f6d"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#eba0ac"
statusbar_bg = "#313244"
statusbar_progress = "#eba0ac"
cmdline = "#eba0ac"
cmdline_bg = "#181825"
