require("config.lazy")
require("config.remap")
require("config.status")
require("config.autocmds")
require("config.lsp")
require("config.greeter")

local highlight = vim.cmd.hi
vim.cmd.colorscheme("kanagawa-wave")
highlight({ args = { "TelescopeBorder", "guibg=NONE" } })
highlight({ args = { "FloatBorder", "guibg=NONE" } })
highlight({ args = { "NormalFloat", "guibg=NONE" } })
highlight({ args = { "FloatTitle", "guibg=NONE" } })
highlight({ args = { "LineNr", "guibg=NONE" } })
highlight({ args = { "DiagnosticSignInfo", "guibg=NONE" } })
highlight({ args = { "DiagnosticSignWarn", "guibg=NONE" } })
highlight({ args = { "DiagnosticSignError", "guibg=NONE" } })
highlight({ args = { "DiagnosticSignHint", "guibg=NONE" } })
highlight({ args = { "StatusLine", "guibg=NONE" } })
highlight({ args = { "SignColumn", "guibg=NONE" } })
highlight({ args = { "CursorLineNr", "guibg=NONE" } })
