preload = ~/Pictures/Wallpapers/Cloudsday.jpg
preload = ~/Pictures/Wallpapers/Cloudsnight.jpg
preload = ~/Pictures/Wallpapers/Rainnight.jpg
preload = ~/Pictures/Wallpapers/mandelbrot_gap_magenta.png
preload = ~/Pictures/Wallpapers/evening-sky.png
preload = ~/Pictures/Wallpapers/marketplace.png
preload = ~/Pictures/Wallpapers/pink_planet.jpg
preload = ~/Pictures/Wallpapers/mandelbrot_side_flamingo.png
preload = ~/Pictures/Wallpapers/pink_space.jpg
preload = ~/Pictures/Wallpapers/wallpaper1.jpg
preload = ~/Pictures/Wallpapers/yosemite.png

wallpaper =,~/Pictures/Wallpapers/pink_space.jpg
splash = false
