preload = ~/Pictures/Wallpapers/alps_lake.png
preload = ~/Pictures/Wallpapers/city_skyline.png
preload = ~/Pictures/Wallpapers/Clearnight.png
preload = ~/Pictures/Wallpapers/Cloudsday.png
preload = ~/Pictures/Wallpapers/dark_space.png
preload = ~/Pictures/Wallpapers/evening-sky.png
preload = ~/Pictures/Wallpapers/green_valley.png
preload = ~/Pictures/Wallpapers/lady_on_cliff.png
preload = ~/Pictures/Wallpapers/lake_mountain.png
preload = ~/Pictures/Wallpapers/mandelbrot_gap_red.png
preload = ~/Pictures/Wallpapers/mandelbrot_gap_sky.png
preload = ~/Pictures/Wallpapers/Rainnight.png
preload = ~/Pictures/Wallpapers/red_desert.png
preload = ~/Pictures/Wallpapers/snowy_alps.png

wallpaper = ,~/Pictures/Wallpapers/dark_space.png
splash = false
