preload = ~/Pictures/Wallpapers/evening-sky.png
preload = ~/Pictures/Wallpapers/green_valley.jpg
preload = ~/Pictures/Wallpapers/lady_on_cliff.png
preload = ~/Pictures/Wallpapers/lake_mountain.jpg
preload = ~/Pictures/Wallpapers/mandelbrot_gap_red.png
preload = ~/Pictures/Wallpapers/Rainnight.jpg
preload = ~/Pictures/Wallpapers/red_desert.jpg
preload = ~/Pictures/Wallpapers/snowy_alps.jpg
preload = ~/Pictures/Wallpapers/alps_lake.jpg
preload = ~/Pictures/Wallpapers/city_skyline.jpg
preload = ~/Pictures/Wallpapers/mandelbrot_gap_sky.png
preload = ~/Pictures/Wallpapers/Clearnight.jpg
preload = ~/Pictures/Wallpapers/Cloudsday.jpg
preload = ~/Pictures/Wallpapers/dark_space.png

wallpaper =,~/Pictures/Wallpapers/red_desert.jpg
splash = false
