themes:
  - name: "immortal"
    colors:
      - "#1a161e"
      - "#1a1720"
      - "#1a1922"
      - "#1a1b24"
      - "#171d27"
      - "#1c2530"
      - "#222e3b"
      - "#293847"
      - "#304252"
      - "#384b5d"
      - "#40566a"
      - "#486277"
      - "#527089"
      - "#5d7e98"
      - "#698da7"
      - "#769bb5"
      - "#83a8c1"
      - "#91b4ca"
      - "#a0c0d2"
      - "#707f8f"
      - "#7b8fa1"
      - "#879bad"
      - "#93a7b9"
      - "#9fb3c5"
      - "#aac0d1"
      - "#b5cbd9"
