fullscreen=yes

hwdec=auto
target-colorspace-hint=no
save-position-on-quit

profile=high-quality
video-sync=display-resample
interpolation

sub-auto=fuzzy
sub-ass-override=strip
sub-color="#EFCF2F"
sub-font=JetBrainsMono Nerd Font Mono
sub-font-size=40
sub-bold=yes

screenshot-directory=~/Pictures/screenshots
screenshot-template=grimshot_%tY-%tm-%td_%tH-%tM-%tS.%tN
screenshot-format=png
